version: "2"
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
exclude_patterns:
  - "**/*.spec.ts"
checks:
  method-lines:
    config:
      threshold: 60
  method-complexity:
    config:
      threshold: 6