branch: "master"
noCI: true
dryRun: false
npmPublish: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/exec", {
      "publishCmd": "./.release.sh ${nextRelease.version}"
    }]